"""Tests des sections dashboard Produits/Commandes et du blog (public + admin)."""

import json

import pytest
from django.contrib.auth import get_user_model
from django.test import Client
from django.urls import reverse

from .models import BlogPost, Order, OrderItem, Product

User = get_user_model()


def _staff(client):
    user = User.objects.create_superuser("boss", "boss@test.com", "password123")
    client.force_login(user)
    return user


def _regular(client):
    user = User.objects.create_user("client1", "c@test.com", "password123")
    client.force_login(user)
    return user


# ── Dashboard Produits ───────────────────────────────────────────

@pytest.mark.django_db
class TestDashboardProducts:
    def test_staff_crud_product(self):
        client = Client()
        _staff(client)
        # create
        r = client.post(reverse("adminpanel:product-create"),
                        data=json.dumps({"name": "Kit", "price_htg": 500, "stock": 10}),
                        content_type="application/json")
        assert r.status_code == 201
        pid = r.json()["id"]
        # list
        assert client.get(reverse("adminpanel:product-list")).status_code == 200
        # update
        r = client.put(reverse("adminpanel:product-detail", args=[pid]),
                       data=json.dumps({"price_htg": 750}), content_type="application/json")
        assert r.status_code == 200 and r.json()["price_htg"] == 750
        # delete
        assert client.delete(reverse("adminpanel:product-detail", args=[pid])).status_code == 200

    def test_delete_product_in_order_blocked(self):
        client = Client()
        _staff(client)
        product = Product.objects.create(name="Kit", price_htg=500, stock=5)
        order = Order.objects.create(customer_name="A", customer_phone="1", delivery_address="X")
        OrderItem.objects.create(order=order, product=product, product_name="Kit", quantity=1, unit_price_htg=500)
        r = client.delete(reverse("adminpanel:product-detail", args=[product.id]))
        assert r.status_code == 409
        assert Product.objects.filter(id=product.id).exists()

    def test_non_staff_blocked(self):
        client = Client()
        _regular(client)
        assert client.get(reverse("adminpanel:product-list")).status_code == 403


# ── Dashboard Commandes ──────────────────────────────────────────

@pytest.mark.django_db
class TestDashboardOrders:
    def test_status_update(self):
        client = Client()
        _staff(client)
        order = Order.objects.create(customer_name="A", customer_phone="1", delivery_address="X")
        r = client.put(reverse("adminpanel:order-detail", args=[order.id]),
                       data=json.dumps({"status": "shipped"}), content_type="application/json")
        assert r.status_code == 200
        order.refresh_from_db()
        assert order.status == Order.Status.SHIPPED


# ── Blog ─────────────────────────────────────────────────────────

@pytest.mark.django_db
class TestBlog:
    def test_dashboard_create_and_public_visibility(self):
        client = Client()
        _staff(client)
        r = client.post(reverse("adminpanel:blog-create"),
                        data=json.dumps({"title": "Bien épargner", "body": "Corps de l'article.", "status": "published"}),
                        content_type="application/json")
        assert r.status_code == 201
        post = BlogPost.objects.get(id=r.json()["id"])
        assert post.published_at is not None  # auto-renseigné à la publication

        # Public : liste + détail visibles
        public = Client()
        resp = public.get(reverse("core:blog_list"))
        assert resp.status_code == 200
        assert b"Bien" in resp.content
        detail = public.get(reverse("core:blog_detail", args=[post.slug]))
        assert detail.status_code == 200

    def test_draft_not_public(self):
        draft = BlogPost.objects.create(title="Brouillon secret", body="…", status=BlogPost.Status.DRAFT)
        public = Client()
        # Absent de la liste
        resp = public.get(reverse("core:blog_list"))
        assert b"Brouillon secret" not in resp.content
        # Détail introuvable (404)
        assert public.get(reverse("core:blog_detail", args=[draft.slug])).status_code == 404

    def test_slug_autogenerated(self):
        post = BlogPost.objects.create(title="Mon Premier Article", body="x")
        assert post.slug == "mon-premier-article"
