"""Tests de la boutique du kit (Product / Order / paiement manuel)."""

import json

import pytest
from django.core.cache import cache
from django.test import Client

from .models import Order, Payment, PaymentProvider, Product


@pytest.fixture(autouse=True)
def _clear_cache():
    cache.clear()
    yield


def _product(**kw):
    defaults = dict(name="Kit éducation financière", kind=Product.Kind.KIT, price_htg=500, stock=10)
    defaults.update(kw)
    return Product.objects.create(**defaults)


@pytest.mark.django_db
class TestProductListing:
    def test_only_active_products_listed(self):
        _product(name="Kit actif", is_active=True)
        _product(name="Kit inactif", is_active=False)
        client = Client()
        resp = client.get("/api/products/")
        assert resp.status_code == 200
        data = resp.json()
        names = [p["name"] for p in data]
        assert "Kit actif" in names
        assert "Kit inactif" not in names

    def test_product_slug_autogenerated(self):
        p = _product(name="Livre Épargne")
        assert p.slug  # généré automatiquement


@pytest.mark.django_db
class TestOrderCreation:
    def test_total_computed_server_side(self):
        product = _product(price_htg=500)
        client = Client()
        payload = {
            "customer_name": "Marie Pierre",
            "customer_phone": "509",
            "delivery_address": "Rue X",
            "city": "PAP",
            # Prix piégé envoyé par le client : doit être IGNORÉ.
            "items": [{"product_id": product.id, "quantity": 2, "unit_price_htg": 1}],
        }
        resp = client.post("/api/orders/", data=json.dumps(payload), content_type="application/json")
        assert resp.status_code == 201
        data = resp.json()
        assert data["ok"] is True
        assert data["total_htg"] == 1000  # 2 × 500, pas 2 × 1
        assert data["payment_url"] == f"/paiement/commande/{data['id']}/"
        order = Order.objects.get(id=data["id"])
        assert order.total_htg == 1000
        assert order.items.count() == 1

    def test_missing_fields_rejected(self):
        product = _product()
        client = Client()
        payload = {"items": [{"product_id": product.id, "quantity": 1}]}
        resp = client.post("/api/orders/", data=json.dumps(payload), content_type="application/json")
        assert resp.status_code == 400
        assert "errors" in resp.json()

    def test_empty_cart_rejected(self):
        client = Client()
        payload = {"customer_name": "A", "customer_phone": "1", "delivery_address": "X", "items": []}
        resp = client.post("/api/orders/", data=json.dumps(payload), content_type="application/json")
        assert resp.status_code == 400

    def test_invalid_product_only_rejected(self):
        client = Client()
        payload = {
            "customer_name": "A", "customer_phone": "1", "delivery_address": "X",
            "items": [{"product_id": 99999, "quantity": 1}],
        }
        resp = client.post("/api/orders/", data=json.dumps(payload), content_type="application/json")
        assert resp.status_code == 400
        assert not Order.objects.exists()  # commande annulée (rollback)


@pytest.mark.django_db
class TestOrderPaymentFlow:
    def test_manual_payment_creates_linked_payment(self):
        product = _product(price_htg=750)
        provider = PaymentProvider.objects.create(
            name="MonCash IMSO", provider_type=PaymentProvider.ProviderType.MONCASH, is_active=True,
            instructions="Envoyez au 509-0000",
        )
        client = Client()
        order_payload = {
            "customer_name": "Jean", "customer_phone": "509", "delivery_address": "Rue X",
            "items": [{"product_id": product.id, "quantity": 2}],
        }
        r1 = client.post("/api/orders/", data=json.dumps(order_payload), content_type="application/json")
        order_id = r1.json()["id"]

        r2 = client.post(
            f"/api/paiement/commande/{order_id}/",
            data=json.dumps({"provider_id": provider.id}),
            content_type="application/json",
        )
        assert r2.status_code == 200
        pay = Payment.objects.get(order_id=order_id)
        assert pay.purpose == Payment.Purpose.PRODUCT
        assert pay.amount_htg == 1500  # 2 × 750
        assert pay.status == Payment.Status.PENDING

    def test_paid_payment_marks_order_and_decrements_stock(self):
        product = _product(price_htg=500, stock=10)
        order = Order.objects.create(
            customer_name="Jean", customer_phone="509", delivery_address="Rue X",
        )
        from .models import OrderItem
        OrderItem.objects.create(order=order, product=product, product_name=product.name, quantity=3, unit_price_htg=500)
        order.recompute_total()
        order.save()

        payment = Payment.objects.create(
            purpose=Payment.Purpose.PRODUCT, order=order, amount_htg=1500,
            payer_name="Jean", status=Payment.Status.PENDING,
        )
        # Validation par l'admin : passage à PAID.
        payment.status = Payment.Status.PAID
        payment.save()

        order.refresh_from_db()
        product.refresh_from_db()
        assert order.status == Order.Status.PAID
        assert product.stock == 7  # 10 - 3
