from django.urls import include, path

from .views import (
    DashboardView,
    admin_user_create,
    admin_user_detail,
    admin_user_list,
    blog_create,
    blog_detail,
    blog_list,
    booking_detail,
    booking_list,
    site_settings_detail,
    upload_image,
    contact_detail,
    contact_list,
    chapter_create,
    chapter_detail,
    chapter_list,
    chapter_reorder,
    chapter_video_confirm,
    chapter_video_remove,
    chapter_video_upload_url,
    course_create,
    course_detail,
    course_list,
    course_overview,
    dashboard_charts,
    dashboard_summary,
    enrollment_detail,
    enrollment_list,
    export_csv,
    gei_create,
    gei_detail,
    gei_list,
    gei_overview,
    member_create,
    member_detail,
    member_list,
    member_overview,
    order_detail,
    order_list,
    product_create,
    product_detail,
    product_list,
    notification_check,
    notification_list,
    notification_read,
    notification_read_all,
    payment_detail,
    payment_list,
    provider_create,
    provider_detail,
    provider_list,
    testimonial_create,
    testimonial_detail,
    testimonial_list,
)

app_name = "adminpanel"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("api/summary/", dashboard_summary, name="summary"),
    path("api/v1/summary/", dashboard_summary, name="summary-v1"),
    path("api/charts/", dashboard_charts, name="charts"),
    path("api/members/", member_list, name="member-list"),
    path("api/members/overview/", member_overview, name="member-overview"),
    path("api/v1/members/", member_list, name="member-list-v1"),
    path("api/members/create/", member_create, name="member-create"),
    path("api/v1/members/create/", member_create, name="member-create-v1"),
    path("api/members/<int:pk>/", member_detail, name="member-detail"),
    path("api/v1/members/<int:pk>/", member_detail, name="member-detail-v1"),
    path("api/courses/", course_list, name="course-list"),
    path("api/courses/overview/", course_overview, name="course-overview"),
    path("api/courses/<int:course_pk>/chapters/", chapter_list, name="chapter-list"),
    path("api/courses/<int:course_pk>/chapters/create/", chapter_create, name="chapter-create"),
    path("api/courses/<int:course_pk>/chapters/reorder/", chapter_reorder, name="chapter-reorder"),
    path("api/chapters/<int:pk>/", chapter_detail, name="chapter-detail"),
    path("api/chapters/<int:pk>/video-upload-url/", chapter_video_upload_url, name="chapter-video-url"),
    path("api/chapters/<int:pk>/video-confirm/", chapter_video_confirm, name="chapter-video-confirm"),
    path("api/chapters/<int:pk>/video-remove/", chapter_video_remove, name="chapter-video-remove"),
    path("api/v1/courses/", course_list, name="course-list-v1"),
    path("api/courses/create/", course_create, name="course-create"),
    path("api/v1/courses/create/", course_create, name="course-create-v1"),
    path("api/courses/<int:pk>/", course_detail, name="course-detail"),
    path("api/v1/courses/<int:pk>/", course_detail, name="course-detail-v1"),
    path("api/bookings/", booking_list, name="booking-list"),
    path("api/v1/bookings/", booking_list, name="booking-list-v1"),
    path("api/bookings/<int:pk>/", booking_detail, name="booking-detail"),
    path("api/v1/bookings/<int:pk>/", booking_detail, name="booking-detail-v1"),
    path("api/payments/", payment_list, name="payment-list"),
    path("api/v1/payments/", payment_list, name="payment-list-v1"),
    path("api/payments/<int:pk>/", payment_detail, name="payment-detail"),
    path("api/v1/payments/<int:pk>/", payment_detail, name="payment-detail-v1"),
    path("api/contacts/", contact_list, name="contact-list"),
    path("api/v1/contacts/", contact_list, name="contact-list-v1"),
    path("api/contacts/<int:pk>/", contact_detail, name="contact-detail"),
    path("api/v1/contacts/<int:pk>/", contact_detail, name="contact-detail-v1"),
    path("api/geis/", gei_list, name="gei-list"),
    path("api/geis/overview/", gei_overview, name="gei-overview"),
    path("api/v1/geis/", gei_list, name="gei-list-v1"),
    path("api/geis/create/", gei_create, name="gei-create"),
    path("api/v1/geis/create/", gei_create, name="gei-create-v1"),
    path("api/geis/<int:pk>/", gei_detail, name="gei-detail"),
    path("api/v1/geis/<int:pk>/", gei_detail, name="gei-detail-v1"),
    path("api/providers/", provider_list, name="provider-list"),
    path("api/v1/providers/", provider_list, name="provider-list-v1"),
    path("api/providers/create/", provider_create, name="provider-create"),
    path("api/v1/providers/create/", provider_create, name="provider-create-v1"),
    path("api/providers/<int:pk>/", provider_detail, name="provider-detail"),
    path("api/v1/providers/<int:pk>/", provider_detail, name="provider-detail-v1"),
    path("api/enrollments/", enrollment_list, name="enrollment-list"),
    path("api/v1/enrollments/", enrollment_list, name="enrollment-list-v1"),
    path("api/enrollments/<int:pk>/", enrollment_detail, name="enrollment-detail"),
    path("api/v1/enrollments/<int:pk>/", enrollment_detail, name="enrollment-detail-v1"),
    path("api/notifications/", notification_list, name="notification-list"),
    path("api/v1/notifications/", notification_list, name="notification-list-v1"),
    path("api/notifications/check/", notification_check, name="notification-check"),
    path("api/v1/notifications/check/", notification_check, name="notification-check-v1"),
    path("api/notifications/<int:pk>/read/", notification_read, name="notification-read"),
    path("api/v1/notifications/<int:pk>/read/", notification_read, name="notification-read-v1"),
    path("api/notifications/read-all/", notification_read_all, name="notification-read-all"),
    path("api/v1/notifications/read-all/", notification_read_all, name="notification-read-all-v1"),
    path("api/testimonials/", testimonial_list, name="testimonial-list"),
    path("api/v1/testimonials/", testimonial_list, name="testimonial-list-v1"),
    path("api/testimonials/create/", testimonial_create, name="testimonial-create"),
    path("api/v1/testimonials/create/", testimonial_create, name="testimonial-create-v1"),
    path("api/testimonials/<int:pk>/", testimonial_detail, name="testimonial-detail"),
    path("api/v1/testimonials/<int:pk>/", testimonial_detail, name="testimonial-detail-v1"),
    path("api/products/", product_list, name="product-list"),
    path("api/products/create/", product_create, name="product-create"),
    path("api/products/<int:pk>/", product_detail, name="product-detail"),
    path("api/orders/", order_list, name="order-list"),
    path("api/orders/<int:pk>/", order_detail, name="order-detail"),
    path("api/blog/", blog_list, name="blog-list"),
    path("api/blog/create/", blog_create, name="blog-create"),
    path("api/blog/<int:pk>/", blog_detail, name="blog-detail"),
    path("api/settings/", site_settings_detail, name="settings-detail"),
    path("api/upload/<str:target>/<int:pk>/", upload_image, name="upload-image"),
    path("api/admins/", admin_user_list, name="admin-list"),
    path("api/admins/create/", admin_user_create, name="admin-create"),
    path("api/admins/<int:pk>/", admin_user_detail, name="admin-detail"),
    path("api/export/<str:model_name>/", export_csv, name="export-csv"),
]

from .routers import router

urlpatterns += [
    path("api/v2/", include(router.urls)),
]
