# Generated by Django 5.2.15 on 2026-06-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('manual', 'Paiement manuel'), ('moncash', 'MonCash'), ('natcash', 'NatCash'), ('bank', 'Virement bancaire'), ('cash', 'Cash'), ('stripe', 'Stripe'), ('other', 'Autre')], default='manual', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text='Texte montre au client: numero MonCash, compte bancaire, consignes, etc.')),
                ('checkout_url', models.URLField(blank=True, help_text='Lien de paiement externe optionnel. Laisse vide pour un paiement manuel.')),
                ('api_public_key', models.CharField(blank=True, max_length=255)),
                ('api_secret_key', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='venuebooking',
            name='setup',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='venuebooking',
            name='status',
            field=models.CharField(choices=[('requested', 'Demandee'), ('payment_pending', 'Paiement attendu'), ('admin_review', 'Paiement recu - validation admin'), ('confirmed', 'Confirmee'), ('cancelled', 'Annulee')], default='requested', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('purpose', models.CharField(choices=[('venue', 'Reservation de salle'), ('course', 'Inscription cours'), ('membership', 'Adhesion'), ('other', 'Autre')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Paye'), ('failed', 'Echoue'), ('cancelled', 'Annule'), ('refunded', 'Rembourse')], default='pending', max_length=20)),
                ('entry_mode', models.CharField(choices=[('manual', 'Saisie manuelle'), ('api', 'API'), ('client', 'Client')], default='client', max_length=20)),
                ('payer_name', models.CharField(max_length=140)),
                ('payer_phone', models.CharField(blank=True, max_length=40)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('amount_htg', models.PositiveIntegerField(default=0)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='adminpanel.enrollment')),
                ('venue_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='adminpanel.venuebooking')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='adminpanel.paymentprovider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
