# Generated by Django 5.2.15 on 2026-06-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('notification_type', models.CharField(choices=[('new_booking', 'Nouvelle réservation'), ('new_payment', 'Nouveau paiement'), ('new_contact', 'Nouveau message'), ('new_enrollment', 'Nouvelle inscription'), ('payment_received', 'Paiement reçu'), ('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée')], max_length=30)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
