# Generated by Django 5.2.15 on 2026-06-10 17:02

import apps.adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_add_screenshot_to_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=140)),
                ('author_initials', models.CharField(blank=True, help_text='Ex: MJ, JV', max_length=6)),
                ('location', models.CharField(blank=True, help_text='Ex: GEI Pétion-Ville · 2 ans', max_length=140)),
                ('text', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='testimonials/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='api_secret_key',
            field=apps.adminpanel.models.EncryptedCharField(blank=True, max_length=512),
        ),
    ]
