# Generated by Django 5.2.15 on 2026-07-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='IMSO', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Impact Mutuelle de Solidarité', max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='site/')),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=60)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('color_primary', models.CharField(blank=True, default='#3C9626', help_text='Couleur principale (hex)', max_length=9)),
                ('color_primary_dark', models.CharField(blank=True, default='#2A6E1B', max_length=9)),
                ('color_accent', models.CharField(blank=True, default='#5BB143', max_length=9)),
                ('color_highlight', models.CharField(blank=True, default='#E87A18', max_length=9)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_cta_text', models.CharField(blank=True, default='Adhérer', max_length=60)),
                ('about_title', models.CharField(blank=True, max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('shop_intro', models.TextField(blank=True, help_text="Texte d'intro de la boutique")),
                ('footer_text', models.TextField(blank=True)),
                ('show_shop', models.BooleanField(default=True)),
                ('show_blog', models.BooleanField(default=True)),
                ('show_courses', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Affiche un bandeau maintenance')),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
