# Generated by Django 5.2.15 on 2026-07-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_chaptercompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_document',
            field=models.FileField(blank=True, upload_to='kyc/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'Non soumis'), ('submitted', 'En attente de vérification'), ('approved', 'Vérifié'), ('rejected', 'Rejeté')], default='not_submitted', max_length=20),
        ),
    ]
