# Generated by Django 5.2.15 on 2026-07-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_profile_id_document_profile_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovider',
            name='account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='account_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='logo',
            field=models.FileField(blank=True, upload_to='payment_logos/'),
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='mode',
            field=models.CharField(choices=[('manual', 'Manuel (le client paie puis on confirme)'), ('api', 'API (paiement en ligne automatisé)')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentprovider',
            name='provider_type',
            field=models.CharField(choices=[('manual', 'Paiement manuel'), ('moncash', 'MonCash'), ('natcash', 'NatCash'), ('bank', 'Virement bancaire'), ('cash', 'Cash'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('other', 'Autre')], default='manual', max_length=30),
        ),
    ]
