# Generated by Django 5.2.15 on 2026-07-05 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_paymentprovider_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status'], name='adminpanel__status_14c299_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['status'], name='adminpanel__status_f6e48f_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['-created_at'], name='adminpanel__created_cafc16_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='adminpanel__status_00ba18_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='adminpanel__created_dfd4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='adminpanel__status_b61766_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['purpose'], name='adminpanel__purpose_a2a16b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='adminpanel__created_037a56_idx'),
        ),
        migrations.AddIndex(
            model_name='venuebooking',
            index=models.Index(fields=['status'], name='adminpanel__status_785031_idx'),
        ),
        migrations.AddIndex(
            model_name='venuebooking',
            index=models.Index(fields=['-created_at'], name='adminpanel__created_ae14ae_idx'),
        ),
    ]
