# Generated by Django 5.2.15 on 2026-07-06 03:00

import apps.adminpanel.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_courseenrollment_adminpanel__status_14c299_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='video',
            field=models.FileField(blank=True, storage=apps.adminpanel.storage.private_media_storage, upload_to='courses/videos/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.FileField(blank=True, storage=apps.adminpanel.storage.private_media_storage, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.FileField(blank=True, storage=apps.adminpanel.storage.private_media_storage, upload_to='kyc/'),
        ),
    ]
