# Generated by Django 5.2.15 on 2026-07-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_alter_chapter_video_alter_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
    ]
