# Generated by Django 5.2.15 on 2026-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_rls_deny_public_api_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji affiche (ex. 🤝, 🌱). Laisse vide pour une icone par defaut.', max_length=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('meta', models.CharField(blank=True, help_text='Duree / info courte (ex. « ⏱ 1 semaine »).', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='formation_hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='formation_hero_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_growth',
            field=models.CharField(blank=True, help_text='Ex: +38%', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_growth_label',
            field=models.CharField(blank=True, help_text='Ex: Épargne collective', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_members',
            field=models.CharField(blank=True, help_text='Ex: 248 membres', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_members_label',
            field=models.CharField(blank=True, help_text='Ex: Actifs en avril 2026', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_repayment',
            field=models.CharField(blank=True, help_text='Ex: 96%', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_repayment_label',
            field=models.CharField(blank=True, help_text='Ex: Taux de remboursement', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_savings',
            field=models.CharField(blank=True, help_text='Ex: 3.2M', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_savings_label',
            field=models.CharField(blank=True, help_text="Ex: HTG d'épargne mobilisée", max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_women',
            field=models.CharField(blank=True, help_text='Ex: 61%', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_women_label',
            field=models.CharField(blank=True, help_text='Ex: Membres femmes', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_workshops',
            field=models.CharField(blank=True, help_text='Ex: 52', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_workshops_label',
            field=models.CharField(blank=True, help_text='Ex: Ateliers tenus en 2025', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_calendrier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_confidentialite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_mentions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_mentor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_presse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_rapport',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='url_statuts',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
