# Generated by Django 5.2.15 on 2026-07-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_seed_site_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(help_text="Description lisible pour l'admin", max_length=200)),
                ('group', models.CharField(blank=True, help_text="Section/page (regroupement dans l'admin)", max_length=60)),
                ('image', models.FileField(blank=True, upload_to='site/images/')),
                ('alt', models.CharField(blank=True, help_text='Texte alternatif (accessibilite/SEO)', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'key'],
            },
        ),
    ]
