# Generated by Django 5.2.15 on 2026-07-09 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0025_seed_site_texts_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, help_text='Rôle/mission de cet admin', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accès administrateur',
                'verbose_name_plural': 'Accès administrateurs',
            },
        ),
    ]
