# Generated by Django 5.2.15 on 2026-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0029_ratelimit_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='icon',
            field=models.CharField(blank=True, help_text="Emoji optionnel (ex. 📝) affiche a la place du numero d'etape.", max_length=8),
        ),
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.FileField(blank=True, help_text="Image optionnelle illustrant l'etape.", upload_to='site/steps/'),
        ),
    ]
