# Generated by Django 5.2.15 on 2026-07-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0032_delete_dashboardmetric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=False, help_text='Si activé, la boutique refuse une commande dépassant le stock disponible.'),
        ),
    ]
