# Generated by Django 5.2.15 on 2026-07-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_product_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='venue_price_htg',
            field=models.PositiveIntegerField(default=0, help_text="Prix de location de la salle (HTG) facturé lors d'une réservation. 0 = aucun montant."),
        ),
    ]
